name: Release with commit

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/release-with-commit@v2.4.0
        with:
          regexp: "^Version ((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*))(?:[ \\t]?(.+)?\\s+((?:\\s|.+)(?:\\s|.+)+))?$"
          regexp_options: "usi"
          release_name: "Version $1"
          tag_name: "v$1"
          body: "$6"
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
